name: Deploy
on: [push]
jobs:
  deploy:
    name: git-ftp
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: git-ftp push
      uses: sebastianpopp/git-ftp-action@releases/v3
      with:
        url: "ftp://210.206.179.221:9091"
        user: ${{ secrets.username }}
        password: ${{ secrets.password }}
